### ISSUE TITLE
Presentation Info

### ISSUE THREAD

**Issue by ghost** [projectgoav/studeso#37]
After a series of emails from Leif today there's a few things I want to check:
- Are we still sticking to what we said before where we wanted everything uploaded today? We have until Friday to commit all changes to the repo in case we fix bugs/add anything else after the presentation (@projectgoav you still okay with that?)
- Leif is insisting on an account where the username and password is 'test' so I will add this to the population script
- We also need to resubmit the powerpoint to reflect what we currently have (take it not much needs altered apart from the ER diagram? Or is there anything else that needs changed?)
- The assessment sheet needs to be handed to Leif on Wednesday and electronically submitted. I can print a copy of it off and we can fill in all the details on Monday before the presentation.
- Speaking of which, how can we agree on the contribution percentages? Should we use the number of commits or the number of additions to the repo?

**Comment by projectgoav** [comment]
I don't mind about commit time. I'm sick to the back teeth of coding webapps, so once we've done the presentations I probably wont be working as much on it as I have JOOSE and other stuff to do next week which was planned before this new deadline came.

Dunno about presentation, we can see when we've stopping updating & fixing stuff.

Don't use additions. I've added a couple of JS and JSON pages which all have many hundreds of lines. I also added the boostrap css and js files which are massive so count as a large number of additions, meaning everything would be weighted more in my favour, which is unfair.

**Comment by ghost** [comment]
I think after we present it we should probably leave the repo alone unless there's something majorly wrong.

I'll try and determine who deserves what percentage contribution and let you know

**Comment by mmckay99** [comment]
I think any measure of code metric / github commits would be inherently unfair.

 I propose we all agree on 25% each- I think we've all worked equally hard to the best of our abilities.

**Comment by ghost** [comment]
I agree with you Michael but I'd feel bad given the fact that everyone else has done so much more work

**Comment by projectgoav** [comment]
I'm not trying to sound a dick or ignorant or anything like thar, but it did appear to me that myself and Paul did do a bit more of code for the site, which is one of biggest bits of the project. I know not everyone has the same love of coding as perhaps I do or even the free time to put into the project but I'd maybe like to suggest a 30/30, 20/20 split between Paul and I and Michael and Lewis. 

However I would like to add that I think everyone did put in an awful lot of effort and I'd like to thank you for that! What do you think?

**Comment by ghost** [comment]
That's the point I was trying to get across, I mean Ewan did a lot with the registration framework and Paul set up the models and did a lot about the likes etc. I'm happy for a 30/30/20/20 split

**Comment by mmckay99** [comment]
Sorry but I am going to need more convincing for a 30, 30, 20, 20. 

Ewan, your work in the registration is great and all but we agreed at the start that you'd be doing it off your own back, on your own time (rather than us using django-registration-redux). You contributed a large part of the project in the form of excellent sign up package and less to the main views and templates.

How much code we wrote **is not** a good metric, and as above we would be here for weeks figuring out what is. I think Paul put in much more man-hours than any of us, but Lewis clearly showed excellent motivation and spent time getting Qs working and deserves as much credit as anyone. I spent a long time myself getting the "or" search to work- it's a complicated piece of code.

I think we're a team, at the end of the day there was no complaints from anyone about the workload during the project, and **we all did as much as we could.**

**Comment by ghost** [comment]
Let's not argue now we've done so well to get to where we are! I honestly think the best way to settle this is before the presentation on Monday

**Comment by projectgoav** [comment]
If Paul has done the most work and has spent the most man-hours on it, then I think he deserves more than a 25% share.

**Comment by projectgoav** [comment]
Re to what I said last night. We're never going to agree on who gets what so in in the it's probably best with a 25% share each.  Saves hassle and stops us fighting amongst ourselves.

I have to disagree with Michael saying that code metrics shouldn't be used in cases like these. Perhaps not use them entirely to make judgement but that suggests that if we were in the state like some teams that someone has just disappeared and not done anything since they first formed the team, they'd still be entitled to 25% contribution because they had a good idea and/or turned up to a meeting. 

However, with that settled, do we need a printed copy as well as an electronic copy? I'll print one out and bring it along with me tomorrow. Who's going to email a copy along with the updated presentation?

**Comment by ghost** [comment]
Yeah Leif needs a printed one on Wednesday, I can send him the updated powerpoint.

If we fill it in tomorrow, I can scan it in and send it to him then return it back to somebody Tuesday so it can be given to Leif Wednesday when I'm not there
