### ISSUE TITLE
Stuff to do before Monday

### ISSUE THREAD

**Issue by SCOTPAUL** [projectgoav/studeso#4]
- URL map in presentation
- Site map in presentation
- Functional Requirements in presentation
- Screenshots of wireframes - added but need updated after mockups updated
- Add 'Make a Post' link to template - then screenshots will need updated

**Comment by ghost** [comment]
Screenshots have been added to the powerpoint but will need updated once the 'make a post' link is added
URL/Site-Map still needs added as well as updating the functional requirements
I also added the list of who is saying what on Monday (because @mmckay99  never pushed his commits pfft)

Also @SCOTPAUL has kindly agreed to print off the presentation! :+1:
